# Generated by Django 5.0 on 2024-02-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField(verbose_name='Sepete Eklenen Adet')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='sepete eklenme tarihi')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Güncelleme Tarihi')),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sepete Ekleyen')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sepete Eklenen Ürün')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Sepetteki Ürünler',
            },
        ),
    ]
